name: Manual Update Tracking

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Chrome and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          pip install selenium webdriver-manager

      - name: Run Scraper
        run: |
          cd tracking-folder
          python scraper.py
          ls -l  # מדפיס את רשימת הקבצים בתיקייה כדי שנוכל לראות אם ה-JSON נוצר

      - name: Commit and Push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # מוסיף את הקובץ ישירות מהנתיב שלו
          git add tracking-folder/tracking_data.json
          
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update tracking data [skip ci]"
            git push
          fi
